### ISSUE TITLE
question about trimming adapter

### ISSUE THREAD

**Issue by Flower9618** [yos-sk/nanoEM#1]
Hi, thanks for sharing this useful tool.

Can I ask which tool do you use to trim adapter for nanoEM dataset before mapping to the reference genome?

**Comment by yos-sk** [comment]
Thank you for your comment and I'm sorry for late response.

Do you mean that the adapter is Illumina adapter?  
I don't conduct adapter trimming  because I don't know adequate tools for nanoEM dataset.

**Comment by yos-sk** [comment]
I close this issue.
