### ISSUE TITLE
[main_samview] fail to read the header from "-".

### ISSUE THREAD

**Issue by Coracollar** [yos-sk/nanoEM#2]
Hi, thank you for the tool. I have been trying to use it but I don't seem to get past mapping. 

If I use minimap2/2.22 it goes incredibly slowly for a 24Gb fastq that should be mapped relatively faster, and haven't manage to make it finish before being killed. And with version 2.17-r941 that is the main one I use I keep having the same error:

[M::main::8.852*0.60] loaded/built the index for 34 target sequence(s)
[M::mm_mapopt_update::9.007*0.61] mid_occ = 21211
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 34
[M::mm_idx_stat::9.115*0.62] distinct minimizers: 7329827 (9.49% are singletons); average occurrences: 107.956; average spacing: 5.271
[main_samview] fail to read the header from "-".
samtools sort: failed to read header from "-"

I've explored my fastq files and the genome and they seem normal, not sure what might be happening. Any idea what might be going wrong?  

Thanks,
Cora

**Comment by yos-sk** [comment]
Thank you for your comment. I'm sorry for late response.

I think some errors occur in header lines of your sam file (probably the process of "samtools view -b"). 
Could you try "samtools view -hb" instead of "samtools view -b"?

**Comment by yos-sk** [comment]
I closed this issue.
